### ISSUE TITLE
What's up here?

### ISSUE THREAD

**Issue by godlyblade** [analogdevicesinc/aducm355-examples#1]
We are waiting for month for some working examples here...

**Comment by mhennerich** [comment]
I had the same question recently and asked @neoanalog, he said that the examples are being checked in soon.

**Comment by neoanalog** [comment]
The examples for ADuCM355 is released on ADI FTP site ftp://ftp.analog.com/pub/MicroConverter/ADuCM355/IAR8_32_AndLater/
This repository is for future work that examples use same [ad5940lib ](github.com/analogdevicesinc/ad5940lib)as [ad5940-examples](https://github.com/analogdevicesinc/ad5940-examples).
The current examples in FTP is not compatible with AD5940.
The code would be checked in to this repository soon.
